
export const NATIONALITIES = {
    AU: "AU", 
    BR: "BR", 
    CA: "CA", 
    CH: "CH", 
    DE: "DE", 
    DK: "DK",
    ES: "ES", 
    FI: "FI", 
    FR: "FR", 
    GB: "GB", 
    IE: "IE", 
    IR: "IR", 
    NO: "NO", 
    NL: "NL", 
    NZ: "NZ", 
    TR: "TR", 
    US: "US",
}

export const NATIONALITIES_HUMEN_NAME = {
    [NATIONALITIES.AU]: "Australia", 
    [NATIONALITIES.BR]: "Brazil", 
    [NATIONALITIES.CA]: "Canada", 
    [NATIONALITIES.CH]: "Cinese", 
    [NATIONALITIES.DE]: "German", 
    [NATIONALITIES.DK]: "Denmark",
    [NATIONALITIES.ES]: "Spanish", 
    [NATIONALITIES.FI]: "Finland", 
    [NATIONALITIES.FR]: "France", 
    [NATIONALITIES.GB]: "Great Britain", 
    [NATIONALITIES.IE]: "Ireland", 
    [NATIONALITIES.IR]: "Iran", 
    [NATIONALITIES.NO]: "Norway", 
    [NATIONALITIES.NL]: "Netherlands", 
    [NATIONALITIES.NZ]: "New Zealand", 
    [NATIONALITIES.TR]: "Turkey", 
    [NATIONALITIES.US]: "United States",
}